---
title: "Alex Rajewski's CV"
author: Alex Rajewski
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1rn6s548jcW0THDsa-juUtDRC4CovcMGCg4QElyH2nqg/",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```


Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

```{r, eval=FALSE}
if(params$pdf_mode){
  cat("View this CV online with links at _http://rajewski.github.io/CV/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this #CV](https://github.com/rajewski/resume/rajewski_cv.pdf)")
}
```

The source code<br>for this CV is available<br>[on github.com/rajewski/resume](https://github.com/rajewski/resume).




Main
================================================================================

Alex Rajewski {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Work Experience {data-icon=laptop}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('research_positions')
```

::: aside
```{r}
CV %<>% print_text_block('research_aside')
```
:::

<!-- Industry Experience {data-icon=suitcase} -->
<!-- -------------------------------------------------------------------------------- -->



<!-- ```{r} -->
<!-- CV %<>% print_section('industry_positions') -->
<!-- ``` -->


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('teaching_experience_aside') -->
<!-- ``` -->
<!-- ::: -->

```{r}
CV %<>% print_section('teaching_positions')
```


Peer-Reviewed Publications {data-icon=book}
--------------------------------------------------------------------------------
::: aside
```{r}
CV %<>% print_text_block('academic_articles_aside')
```
:::

```{r}
CV %<>% print_section('academic_articles')
```

Outreach {data-icon=handshake-o}
--------------------------------------------------------------------------------
```{r}
CV %<>% print_section('outreach')
```

Oral and Poster Presentations {data-icon=book}
--------------------------------------------------------------------------------
::: aside
```{r}
CV %<>% print_text_block('poster_experience_aside')
```
:::

```{r}
CV %<>% print_section('oral_poster_presentations')
```


```{r}
CV %<>% print_links()
```
